services:
  ups-nut-static:
    image: kostahiveradar/ups-nut-2.8.4-arm64:0.97
    container_name: ups-nut-static
    restart: unless-stopped
    privileged: true
    platform: linux/arm64
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "3493:3493"
    volumes:
      - ups-nut-state:/var/run/nut
      - ups-nut-logs:/var/log/nut
      - /run/udev:/run/udev:ro
    environment:
      - TZ=UTC
      - SCAN_INTERVAL=999999
      - DEBUG=1
    entrypoint: ["/bin/bash", "-c", "chmod -R 666 /dev/bus/usb/*/* && /opt/nut/sbin/upsdrvctl start && sleep 2 && /opt/nut/sbin/upsd -D -F"]

volumes:
  ups-nut-state:
  ups-nut-logs: