'\" t
.\"     Title: bicker_ser
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/08/2025
.\"    Manual: NUT Manual
.\"    Source: Network UPS Tools 2.8.4
.\"  Language: English
.\"
.TH "BICKER_SER" "8" "08/08/2025" "Network UPS Tools 2\&.8\&.4" "NUT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bicker_ser \- Driver for Bicker DC UPS via serial port connections
.SH "SYNOPSIS"
.sp
\fBbicker_ser\fR \-h
.sp
\fBbicker_ser\fR \-a \fIUPS_NAME\fR [\fIOPTIONS\fR]
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.sp
This man page only documents the hardware\-specific features of the \fBbicker_ser\fR driver\&. For information about the core driver, see \fBnutupsdrv\fR(8)\&.
.sp .5v
.RE
.SH "SUPPORTED HARDWARE"
.sp
\fBbicker_ser\fR supports all Bicker UPSes shipped with the PSZ\-1053 extension module such as UPSIC\-1205, UPSIC\-2403, DC2412\-UPS and DC2412\-UPS\-LD\&.
.SH "CABLING"
.sp
The needed cable is a standard pin\-to\-pin serial cable with pins 2, 3 and 5 (on DB9 connector) connected\&.
.SH "EXTRA ARGUMENTS"
.sp
This driver supports no extra arguments from \fBups.conf\fR(5)\&.
.SH "VARIABLES"
.sp
Depending on the type of your UPS unit, some of the following variables may be changed with \fBupsrw\fR(8)\&. If the driver can\(cqt read a variable from the UPS, it will not be made available\&. Whenever not explicitly stated, any variable can be disabled, in which case the action it performs will not be executed\&. To disable a variable, set it to an empty value\&.
.PP
\fBups\&.delay\&.shutdown\fR (in seconds, default disabled)
.RS 4
If activated and the UPS is in battery mode and the set time has expired, the output will be disabled, and the UPS and energy storage will be disconnected\&.
.RE
.PP
\fBups\&.delay\&.start\fR (in seconds, default disabled)
.RS 4
If activated and a restart condition switches the UPS output off and on again, the set time is the delay between switching on and off\&. The time should cause a defined off time so that capacities in the application can be discharged\&.
.RE
.PP
\fBbattery\&.charge\&.restart\fR (in percent, default disabled)
.RS 4
If activated and the UPS is off or restarts, the UPS output will not be released until the energy storage device has the set charge state\&. The energy storage device is charged in the meantime\&.
.RE
.PP
\fBbattery\&.charge\&.low\fR (in percent, default 20)
.RS 4
If activated and the UPS is in battery mode and the battery level drops below the set value, a shutdown command via relay event is signaled\&.
.RE
.PP
\fBexperimental\&.output\&.current\&.low\fR (in mA, default 200)
.RS 4
If activated and the UPS is in battery mode and the current drops below the set value, the output of the UPS will shut down and disconnect the energy storage to prevent self\-discharge\&.
.RE
.PP
\fBexperimental\&.ups\&.delay\&.shutdown\&.signal\fR (in seconds, default disabled)
.RS 4
If activated and the UPS is in battery mode and the set time has elapsed, a shutdown command via relay event is signaled\&.
.RE
.PP
\fBexperimental\&.ups\&.delay\&.shutdown\&.signal\&.masked\fR (in seconds, default disabled)
.RS 4
If activated and the UPS is in battery mode and the signal at the IN\-1 input is high and the set time has expired, a shutdown command via relay event is signaled\&.
.RE
.PP
\fBexperimental\&.battery\&.charge\&.low\&.empty\fR (in percent, default 20)
.RS 4
This parameter stores the threshold value for the "Battery Empty" signal\&. Currently this setting is only valid for relay signaling\&. Cannot be disabled\&.
.RE
.PP
\fBexperimental\&.ups\&.relay\&.mode\fR (default 0x01)
.RS 4
This parameter controls the behavior of the relay in case of different events\&. Cannot be disabled\&.
.sp
Available relay modes:
.TS
tab(:);
lt lt
lt lt
lt lt
lt lt
lt lt.
T{
0x01
T}:T{
On power fail (normally closed)
T}
T{
0x02
T}:T{
On power fail (normally opened)
T}
T{
0x03
T}:T{
Shutdown impulse (1 second)
T}
T{
0x04
T}:T{
Battery low signal (normally closed)
T}
T{
0x05
T}:T{
Battery defect signal (normally closed)
T}
.TE
.sp 1
.RE
.SH "INSTANT COMMANDS"
.PP
\fBshutdown\&.return\fR
.RS 4
Turn off the load and return when power is back\&.
.RE
.SH "KNOWN ISSUES AND BUGS"
.PP
\fBups\&.delay\&.shutdown is not honored\fR
.RS 4
Although that delay is properly set when sending the shutdown command, it seems some UPS ignore it and use a fixed 2 seconds delay instead\&.
.RE
.SH "AUTHOR"
.sp
Nicola Fontana <ntd@entidi\&.it>
.SH "SEE ALSO"
.SS "The core driver:"
.sp
\fBnutupsdrv\fR(8)
.SS "Internet resources:"
.sp
The NUT (Network UPS Tools) home page: https://www\&.networkupstools\&.org/historic/v2\&.8\&.4/
