'\" t
.\"     Title: pijuice
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/08/2025
.\"    Manual: NUT Manual
.\"    Source: Network UPS Tools 2.8.4
.\"  Language: English
.\"
.TH "PIJUICE" "8" "08/08/2025" "Network UPS Tools 2\&.8\&.4" "NUT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pijuice \- Driver for UPS in PiJuice HAT
.SH "SYNOPSIS"
.sp
\fBpijuice\fR \-h
.sp
\fBpijuice\fR \-a \fIUPS_NAME\fR [\fIOPTIONS\fR]
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.sp
This man page only documents the hardware\-specific features of the \fBpijuice\fR driver\&. For information about the core driver, see \fBnutupsdrv\fR(8)\&.
.sp .5v
.RE
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.sp
This manual page was hastily adapted from related asem driver man page based on information from the original pull request, and so may not fully apply to PiJuice HAT, patches from experts are welcome\&.
.sp .5v
.RE
.SH "SUPPORTED HARDWARE"
.sp
The \fBpijuice\fR driver supports the portable PiJuice HAT UPS for Raspberry Pi embedded PCs\&.
.SH "EXTRA ARGUMENTS"
.sp
The required parameter for this driver is the I2C bus name:
.PP
\fBport\fR=\fIdev\-node\fR
.RS 4
On the PiJuice HAT, this should be
/dev/i2c\-1\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
You may want to add the driver run\-time unprivileged user (e\&.g\&.
nut) to the
i2c
group as a secondary group \(em typically in
/etc/group
(along with
pijuice, if vendor CLI/GUI/automation packages are also installed), e\&.g\&.
sudo usermod \-a \-G i2c nut\&. Otherwise you may have to run the driver as
root\&.
.sp .5v
.RE
.RE
.SH "INSTALLATION"
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.sp
This section was copied from asem driver man page and may not fully apply to PiJuice HAT, patches are welcome\&.
.sp .5v
.RE
.sp
This driver is specific to the Linux I2C API, and requires the lm_sensors libi2c\-dev or its equivalent to compile\&.
.sp
Beware that the SystemIO memory used by the I2C controller is reserved by ACPI\&. If only a native I2C driver (e\&.g\&. i2c_i801, as of 3\&.5\&.X Linux kernels) is available, then you\(cqll need to relax the ACPI resources check\&. For example, you can boot with the acpi_enforce_resources=lax option\&.
.SH "KNOWN ISSUES AND BUGS"
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.sp
This section was copied from asem driver man page and may not fully apply to PiJuice HAT, patches are welcome\&.
.sp .5v
.RE
.sp
The driver shutdown function is not implemented, so other arrangements must be made to turn off the UPS\&.
.sp
The battery\&.current and input\&.current may be reported as negative, if it is being charged and wall power is plugged into the Pi itself (not the HAT)\&. This reflects the direction of electric current over the GPIO pins; vendor tools like pijuice_cli or pijuice_gui also show this\&. The reported input\&.current value was seen to fluctuate and even change the sign back and forth as the battery\&.charge value rose from zero into tens of percents with this connectivity setup\&.
.sp
If the ups\&.date and ups\&.time look bogus, use vendor tools to set the RTC clock of the HAT (check in Alarms section)\&.
.sp
The battery\&.temperature report may depend on capabilities of the actual battery and methods used to poll it for information\&. Vendor tools provide several settings for tuning this, but they don\(cqt seem to impact what the driver reports (pull requests welcome); bogus negative values were seen\&.
.SH "AUTHORS"
.sp
Andrew Anderson <aander07@gmail\&.com>
.SH "SEE ALSO"
.SS "The core driver:"
.sp
\fBnutupsdrv\fR(8)
.SS "Internet resources:"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Initial pull requests adding this driver:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
https://github\&.com/networkupstools/nut/pull/730
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
https://github\&.com/PiSupply/PiJuice/issues/124
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Product home page:
https://uk\&.pi\-supply\&.com/products/pijuice\-standard
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
The NUT (Network UPS Tools) home page:
https://www\&.networkupstools\&.org/historic/v2\&.8\&.4/
.RE
