'\" t
.\"     Title: riello_ser
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/08/2025
.\"    Manual: NUT Manual
.\"    Source: Network UPS Tools 2.8.4
.\"  Language: English
.\"
.TH "RIELLO_SER" "8" "08/08/2025" "Network UPS Tools 2\&.8\&.4" "NUT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
riello_ser \- Driver for Riello UPS Protocol UPS equipment via serial port connections
.SH "SYNOPSIS"
.sp
\fBriello_ser\fR \-h
.sp
\fBriello_ser\fR \-a \fIUPS_NAME\fR [\fIOPTIONS\fR]
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.sp
This man page only documents the hardware\-specific features of the riello_ser driver\&. For information about the core driver, see \fBnutupsdrv\fR(8)\&.
.sp .5v
.RE
.SH "SUPPORTED HARDWARE"
.sp
riello_ser supports all recent Riello UPS, Aros UPS models which use the Riello UPS GPSER and SENTR protocols\&.
.sp
Older Riello UPS products are not supported\&.
.SH "EXTRA ARGUMENTS"
.sp
You may need to tweak some settings, depending on the make and model of your UPS (see \fBups.conf\fR(5)):
.PP
\fBlocalcalculation\fR
.RS 4
When enabled, driver will calculate values of
battery\&.runtime
and
battery\&.charge
"locally" in the driver\&. This is for some Riello models which provide incorrect values in hardware readings, or none at all\&. This "local calculation" is done according to nominal battery capacity, nominal battery voltage, actual battery charge, maximum and actual UPS load\&.
.sp
You may want to also configure
\fIdefault\&.battery\&.voltage\&.low\fR
and
\fIdefault\&.battery\&.voltage\&.high\fR
in case the built\-in default range (from 10\&.7V to 12\&.9V) does not match your hardware, or give a shot to
\fIdefault\&.battery\&.voltage\&.nominal\fR
(e\&.g\&.
\fI24\fR) if your device does not serve that either\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
Lead (PbAc) battery charge graph is not linear, so guesstimated charge value may not be perfectly accurate\&. However it should be good enough to determine battery actual status and roughly estimate the time it can still power the system\&.
.sp .5v
.RE
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBWarning\fR
.ps -1
.br
This keyword may be deprecated in future releases of the driver, in favor of
runtimecal
and other settings which it requires (as seen in
\fBnutdrv_qx\fR(8),
\fBblazer_ser\fR(8)
and
\fBblazer_usb\fR(8)
drivers)\&.
.sp .5v
.RE
.RE
.SH "AUTHOR"
.sp
Massimo Zampieri
.SH "SEE ALSO"
.SS "Related drivers"
.sp
\fBriello_usb\fR(8)
.SS "The core driver"
.sp
\fBnutupsdrv\fR(8)
.SS "Internet resources"
.sp
The NUT (Network UPS Tools) home page: https://www\&.networkupstools\&.org/historic/v2\&.8\&.4/
