'\" t
.\"     Title: upscli_set_default_connect_timeout
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/08/2025
.\"    Manual: NUT Manual
.\"    Source: Network UPS Tools 2.8.4
.\"  Language: English
.\"
.TH "UPSCLI_SET_DEFAULT_C" "3" "08/08/2025" "Network UPS Tools 2\&.8\&.4" "NUT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
upscli_set_default_connect_timeout \- Configure upsclient module aspect of default timeout for initial connections\&.
.SH "SYNOPSIS"
.sp
.nf
        #include <upsclient\&.h>

        int upscli_set_default_connect_timeout(const char *secs);
.fi
.SH "DESCRIPTION"
.sp
The \fBupscli_set_default_connect_timeout()\fR function assigns upsclient module internal default connection timeout for \fBupscli_connect\fR(3) from a C string which represents a floating\-point non\-negative number (invalid parsing is ignored and does not modify the previously stored value), a NULL argument value sets the internal timeout to \fI0\fR meaning indefinitely blocking (NUT default for this method over at least 20 years)\&.
.sp
While this method can be called explicitly, it is recommended to call the \fBupscli_init_default_connect_timeout\fR(3) for consistent setting from a number of sources with different priority\&.
.SH "RETURN VALUE"
.sp
The \fBupscli_set_default_connect_timeout()\fR function returns \fI0\fR on success (either if the strings was NULL so the built\-in default \fI0\fR is applied, or if its content was valid and its value got applied), or \fI\-1\fR if an error occurs (string was not NULL, and its content was not valid \(em not a number, negative, etc\&.)
.SH "SEE ALSO"
.sp
\fBupscli_connect\fR(3), \fBupscli_tryconnect\fR(3), \fBupscli_init_default_connect_timeout\fR(3), \fBupscli_get_default_connect_timeout\fR(3)
